const {app}=require('electron'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
fs.mkdirSync('.validation',{recursive:true});app.setPath('userData',path.resolve(fs.mkdtempSync('.validation/ui-test-')));app.disableHardwareAcceleration();
let stage='startup',started=false;fs.writeFileSync('.validation/electron-ui.json',JSON.stringify({running:true}));const timer=setTimeout(()=>finish(Error('UI check timed out: '+stage)),30000);
function finish(error){clearTimeout(timer);fs.writeFileSync('.validation/electron-ui.json',JSON.stringify({passed:!error,error:error?`${error.stack}\nStage: ${stage}`:undefined},null,2));app.exit(error?1:0);}
app.on('browser-window-created',(_,win)=>{if(started)return;started=true;win.webContents.setBackgroundThrottling(false);win.webContents.once('did-finish-load',async()=>{try{
 const evaluate=code=>{stage=code;return win.webContents.executeJavaScript(code,true);};
 assert.equal(await evaluate(`document.documentElement.dataset.theme`),'sky');
 assert.equal(await evaluate(`document.getElementById('play').disabled`),true);
 assert.equal(await evaluate(`document.querySelectorAll('.transport-button svg').length`),6);
 assert.equal(await evaluate(`document.querySelectorAll('.workspace-options svg.lucide').length`),2);
 assert.equal(await evaluate(`document.querySelectorAll('.history-controls svg.lucide').length`),3);assert.equal(await evaluate(`getComputedStyle(document.getElementById('undo')).width`),'36px');assert.notEqual(await evaluate(`getComputedStyle(document.getElementById('undo')).backgroundColor`),'rgba(0, 0, 0, 0)');
 const leftBefore=await evaluate(`document.getElementById('track-panel').getBoundingClientRect().width`);
 const divider=await evaluate(`(()=>{const r=document.getElementById('left-divider').getBoundingClientRect();return {x:Math.round(r.x+3),y:Math.round(r.y+120)};})()`);
 win.focus();win.webContents.focus();win.webContents.sendInputEvent({type:'mouseMove',...divider});win.webContents.sendInputEvent({type:'mouseDown',...divider,button:'left',clickCount:1});
 await evaluate(`new Promise(resolve=>requestAnimationFrame(resolve))`);
 win.webContents.sendInputEvent({type:'mouseMove',x:divider.x+50,y:divider.y,button:'left',modifiers:['leftButtonDown']});
 await evaluate(`new Promise(resolve=>requestAnimationFrame(resolve))`);
 win.webContents.sendInputEvent({type:'mouseUp',x:divider.x+50,y:divider.y,button:'left',clickCount:1});
 await evaluate(`new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))`);
 assert.ok(await evaluate(`document.getElementById('track-panel').getBoundingClientRect().width`)>leftBefore+30,JSON.stringify({leftBefore,divider,actual:await evaluate(`({width:document.getElementById('track-panel').getBoundingClientRect().width,settings:localStorage.getItem('mml-studio-workspace-v1'),grid:document.getElementById('workspace').style.gridTemplateColumns})`)}));
 await evaluate(`document.getElementById('toggle-left').click();new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))`);assert.equal(await evaluate(`document.getElementById('track-panel').hidden`),true);assert.ok(await evaluate(`document.querySelector('.editor').getBoundingClientRect().width`)>400);assert.ok(await evaluate(`document.getElementById('note-properties').getBoundingClientRect().width`)>180);
 await evaluate(`document.getElementById('toggle-left').click();document.getElementById('left-divider').dispatchEvent(new MouseEvent('dblclick'));document.getElementById('right-divider').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}));`);
 assert.equal(await evaluate(`JSON.parse(localStorage.getItem('mml-studio-workspace-v1')).right`),250);
 await evaluate(`document.getElementById('right-divider').dispatchEvent(new MouseEvent('dblclick'))`);
 assert.equal(await evaluate(`document.querySelector('.brand img').naturalWidth>0`),true);
 assert.equal(await evaluate(`getComputedStyle(document.querySelector('.note-fields')).display`),'none');
 const fileArrowCenter=await evaluate(`(()=>{const r=document.querySelector('#file-menu .menu-chevron').getBoundingClientRect();return [r.x+r.width/2,r.y+r.height/2]})()`);await evaluate(`document.querySelector('#file-menu summary').click()`);assert.equal(await evaluate(`document.getElementById('file-menu').open`),true);assert.equal(await evaluate(`getComputedStyle(document.querySelector('#file-menu[open] .menu-chevron')).width`),'9px');assert.deepEqual(await evaluate(`(()=>{const r=document.querySelector('#file-menu .menu-chevron').getBoundingClientRect();return [r.x+r.width/2,r.y+r.height/2]})()`),fileArrowCenter);
 await evaluate(`document.querySelector('.editor-caption').click()`);assert.equal(await evaluate(`document.getElementById('file-menu').open`),false);
 await evaluate(`document.querySelector('#export-menu summary').click()`);assert.equal(await evaluate(`document.getElementById('export-menu').open`),true);assert.equal(await evaluate(`getComputedStyle(document.querySelector('#export-menu[open] .menu-chevron')).width`),'9px');assert.equal(await evaluate(`document.querySelector('#theme').parentElement.classList.contains('select-control')`),true);await evaluate(`document.querySelector('#theme').dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}))`);assert.equal(await evaluate(`document.querySelector('#theme').parentElement.classList.contains('open')`),true);await evaluate(`document.querySelector('#theme').dispatchEvent(new Event('change'))`);assert.equal(await evaluate(`document.querySelector('#theme').parentElement.classList.contains('open')`),false);await evaluate(`document.body.dispatchEvent(new KeyboardEvent('keyup',{key:'Escape',bubbles:true}))`);assert.equal(await evaluate(`document.getElementById('export-menu').open`),false);
 await evaluate(`Promise.all([import('./dist/state.js'),import('./dist/commands.js'),import('./dist/inspector.js')]).then(([{state},{refresh},{info}])=>{window.s=state;window.refresh=refresh;window.info=info;
 s.project.instruments=[{name:'Felt Piano',color:'#78e4c4',midiProgram:0},{name:'Warm Strings',color:'#a998e8',midiProgram:48},{name:'Acoustic Bass',color:'#ebba7b',midiProgram:32},{name:'Soft Bells',color:'#7cbad9',midiProgram:10},{name:'Instructions',color:'#f4d35e',isInstructions:true}];
 s.project.notes=Array.from({length:24},(_,i)=>({id:i+1,instrument:i<16?0:1,start:(i%16)*16,length:i<16?12:32,pitch:[60,64,67,72,71,67,64,62][i%8]-(i>=16?12:0),volume:i===0?10:null}));s.active=0;s.selection=new Set([1,2,3]);refresh();document.getElementById('view').scrollTop=(s.topPitch-79)*20;})`);
 assert.equal(await evaluate(`document.getElementById('play').disabled`),false);
 await evaluate(`window.confirm=message=>{window.clearConfirmation=message;return true};document.getElementById('clear-all').click()`);assert.match(await evaluate(`window.clearConfirmation`),/^Delete all 24 notes and instructions from this project\?\nYou can undo this action\.$/);assert.equal(await evaluate(`s.project.notes.length`),0);assert.equal(await evaluate(`document.getElementById('play').disabled&&document.getElementById('clear-all').disabled`),true);await evaluate(`document.getElementById('undo').click()`);assert.equal(await evaluate(`s.project.notes.length`),24);
 const gridCell=await evaluate(`(()=>{const view=document.getElementById('view'),canvas=document.getElementById('canvas'),r=canvas.getBoundingClientRect(),targetPitch=76;view.scrollLeft=0;document.getElementById('draw').click();return {x:Math.round(r.x+62+(128/s.project.grid)*s.zoom*.75),y:Math.round(r.y+30+(s.topPitch-targetPitch)*20-view.scrollTop+10)};})()`);
 win.webContents.sendInputEvent({type:'mouseMove',...gridCell});win.webContents.sendInputEvent({type:'mouseDown',...gridCell,button:'left',clickCount:1});await evaluate(`new Promise(resolve=>requestAnimationFrame(resolve))`);win.webContents.sendInputEvent({type:'mouseUp',...gridCell,button:'left',clickCount:1});
 assert.equal(await evaluate(`s.project.notes.find(n=>n.pitch===76)?.start`),0,'a click in the right half of the first cell must stay in that cell');
 const paintStart=await evaluate(`(()=>{const view=document.getElementById('view'),canvas=document.getElementById('canvas'),r=canvas.getBoundingClientRect(),targetPitch=75;return {x:Math.round(r.x+62+(128/s.project.grid)*s.zoom*.25),y:Math.round(r.y+30+(s.topPitch-targetPitch)*20-view.scrollTop+10)};})()`),paintEnd={x:paintStart.x+Math.round((128/4)*3*3),y:paintStart.y};
 win.webContents.sendInputEvent({type:'mouseMove',...paintStart});win.webContents.sendInputEvent({type:'mouseDown',...paintStart,button:'left',clickCount:1});await evaluate(`new Promise(resolve=>requestAnimationFrame(resolve))`);win.webContents.sendInputEvent({type:'mouseMove',...paintEnd,button:'left',modifiers:['leftButtonDown']});win.webContents.sendInputEvent({type:'mouseUp',...paintEnd,button:'left',clickCount:1});
 assert.deepEqual(await evaluate(`s.project.notes.filter(n=>n.pitch===75).map(n=>n.start)`),[0,32,64,96]);
 await evaluate(`import('./dist/history.js').then(({checkpoint})=>{s.history=[];s.future=[];for(let grid=4;grid<12;grid++){checkpoint();s.project.grid=grid;}})`);
 const undoPoint=await evaluate(`(()=>{const r=document.getElementById('undo').getBoundingClientRect();return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)};})()`);
 win.webContents.sendInputEvent({type:'mouseMove',...undoPoint});win.webContents.sendInputEvent({type:'mouseDown',...undoPoint,button:'left',clickCount:1});
 await new Promise(resolve=>setTimeout(resolve,900));win.webContents.sendInputEvent({type:'mouseUp',...undoPoint,button:'left',clickCount:1});
 const heldGrid=await evaluate(`s.project.grid`);assert.ok(heldGrid<10,`hold should repeat Undo, got grid ${heldGrid}`);
 await new Promise(resolve=>setTimeout(resolve,180));assert.equal(await evaluate(`s.project.grid`),heldGrid,'Undo repeat should stop on release');
 await evaluate(`s.selection=new Set([1,2,3]);info()`);
 assert.equal(await evaluate(`getComputedStyle(document.querySelector('.note-fields')).display`),'block');
 assert.equal(await evaluate(`getComputedStyle(document.querySelectorAll('.instrument-mml')[1]).display`),'none');
 await evaluate(`document.querySelectorAll('.instrument-name')[1].click()`);
 assert.equal(await evaluate(`document.getElementById('editing-instrument').textContent`),'Warm Strings');
 assert.equal(await evaluate(`getComputedStyle(document.querySelectorAll('.instrument-mml')[1]).display`),'flex');
 assert.equal(await evaluate(`getComputedStyle(document.querySelectorAll('.instrument-mml')[0]).display`),'none');
 await evaluate(`document.querySelectorAll('.instrument-name')[0].click();s.selection=new Set([1,2,3]);info();document.activeElement.blur()`);
 assert.equal(await evaluate(`document.querySelector('.instrument-actions').open`),false);
 await evaluate(`document.querySelector('.instrument-actions summary').click()`);assert.equal(await evaluate(`document.querySelector('.instrument-actions').open`),true);
 await evaluate(`document.querySelector('.instrument-actions summary').click();document.activeElement.blur()`);
 for(const width of [900,1320]){
  win.setSize(width,850);await evaluate(`new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))`);
  const overflow=await evaluate(`[...document.querySelectorAll('.app-header,.editor-toolbar,.track-panel,.inspector-panel')].filter(el=>el.scrollWidth>el.clientWidth+1).map(el=>el.className)`);assert.deepEqual(overflow,[]);
  fs.writeFileSync('.validation/ui-'+width+'.png',(await win.webContents.capturePage()).toPNG());
 }
 await evaluate(`document.getElementById('theme').value='midnight';document.getElementById('theme').dispatchEvent(new Event('change'))`);
 assert.equal(await evaluate(`document.documentElement.dataset.theme`),'midnight');
 assert.equal(await evaluate(`JSON.parse(localStorage.getItem('mml-studio-workspace-v1')).theme`),'midnight');
 await evaluate(`new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))`);
 fs.writeFileSync('.validation/ui-midnight.png',(await win.webContents.capturePage()).toPNG());
 await evaluate(`document.getElementById('theme').value='night';document.getElementById('theme').dispatchEvent(new Event('change'))`);
 assert.equal(await evaluate(`getComputedStyle(document.querySelector('.track-panel')).backgroundColor`),'rgb(20, 20, 20)');
 assert.equal(await evaluate(`getComputedStyle(document.documentElement).backgroundColor`),'rgb(13, 13, 13)');
 assert.equal(await evaluate(`getComputedStyle(document.getElementById('left-divider'),'::after').content`),'none');
 assert.equal(await evaluate(`getComputedStyle(document.getElementById('left-divider')).backgroundColor`),'rgba(0, 0, 0, 0)');
 assert.equal(await evaluate(`getComputedStyle(document.getElementById('view'),'::-webkit-scrollbar').width`),'18px');
 assert.equal(await evaluate(`import('./dist/appearance.js').then(m=>m.palette.gridA)`),'#171717');
 await evaluate(`new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))`);
 fs.writeFileSync('.validation/ui-night.png',(await win.webContents.capturePage()).toPNG());
 // Derive the native window icon from the repository's vector source.
 const png=await evaluate(`new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{const canvas=document.createElement('canvas');canvas.width=256;canvas.height=256;canvas.getContext('2d').drawImage(image,0,0,256,256);resolve(canvas.toDataURL('image/png').split(',')[1]);};image.onerror=reject;image.src='assets/logo.svg';})`);
 fs.writeFileSync('assets/logo.png',Buffer.from(png,'base64'));
 const reloaded=new Promise(resolve=>win.webContents.once('did-finish-load',resolve));win.webContents.reload();await reloaded;
 assert.equal(await evaluate(`document.documentElement.dataset.theme`),'night');
 assert.equal(await evaluate(`document.getElementById('right-divider').getAttribute('aria-valuenow')`),'234');finish();
 }catch(error){finish(error);}});});require('../main.cjs');
