// Native DOM + real compiler regression; no physical-speaker claim.
const {app}=require('electron'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
fs.mkdirSync('.validation',{recursive:true});app.setPath('userData',fs.mkdtempSync(path.resolve('.validation/volume-')));app.disableHardwareAcceleration();
let started=false;const checks=[];const timer=setTimeout(()=>finish(Error('Native volume test timed out')),30000);
function finish(error){clearTimeout(timer);fs.writeFileSync('.validation/electron-volume.json',JSON.stringify({passed:!error,error:error?.stack,checks},null,2));app.exit(error?1:0);}
app.on('browser-window-created',(_,win)=>{if(started)return;started=true;win.webContents.once('did-finish-load',async()=>{try{
 const evaluate=code=>win.webContents.executeJavaScript(code,true);
 await evaluate(`Promise.all([import('./dist/state.js'),import('./dist/commands.js'),import('./dist/playback/midi.js'),import('./dist/import/smf.js'),import('./dist/note-clipboard.js'),import('./dist/history.js')]).then(([{state,resetInstrumentView},commands,midi,smf,clipboard,history])=>{window.s=state;window.commands=commands;window.midi=midi;window.smf=smf;window.clip=clipboard;window.historyApi=history;resetInstrumentView();s.project={format:'mml-studio',version:2,grid:4,name:'Volume verification',instruments:[{name:'Piano',color:'#ffaa33',midiProgram:0}],notes:[{id:1,instrument:0,start:0,length:128,pitch:60,volume:13},{id:2,instrument:0,start:0,length:128,pitch:64,volume:5},{id:3,instrument:0,start:32,length:16,pitch:67,volume:null}]};s.active=0;s.selection=new Set([1]);commands.refresh();})`);
 assert.equal(await evaluate(`document.getElementById('volume').value`),'13');assert.match(await evaluate(`document.getElementById('info').textContent`),/effective V13/);
 const velocities=await evaluate(`smf.readSMF(new Uint8Array(midi.compilePlayback(s.project).binary)).events.filter(e=>(e.status>>4)===9).map(e=>[e.tick,e.data[0],e.data[1]])`);
 assert.deepEqual(velocities,[[0,60,110],[0,64,42],[32,67,42]]);checks.push({velocities});
 await evaluate(`const v=document.getElementById('volume');v.value='12';v.dispatchEvent(new Event('change'))`);
 assert.match(await evaluate(`document.getElementById('info').textContent`),/effective V12/);
 await evaluate(`historyApi.undo();s.selection=new Set([1,2]);commands.refresh();clip.copyNotes();clip.setPastePosition(160);clip.pasteNotes()`);
 assert.deepEqual(await evaluate(`s.project.notes.slice(-2).map(n=>n.volume)`),[13,5]);
 await evaluate(`historyApi.undo();s.selection=new Set([1]);commands.refresh();new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))`);
 assert.equal(await evaluate(`s.project.notes.length`),3);checks.push('Inspector change, Undo and clipboard preserve distinct chord volumes');
 await evaluate(`Promise.all([import('./dist/geometry.js'),import('./dist/state.js'),import('./dist/model/serialization.js'),import('./dist/toolbar.js')]).then(([geometry,stateApi,serialization,toolbar])=>{window.geometry=geometry;window.stateApi=stateApi;window.serialization=serialization;window.toolbar=toolbar;});`);
 await evaluate(`s.project.instruments.push({name:'Strings',color:'#88aaff',midiProgram:48});s.project.notes.push({id:4,instrument:1,start:32,length:32,pitch:72,volume:3},{id:5,instrument:1,start:64,length:32,pitch:74,volume:null});s.selection=new Set([1]);commands.refresh();document.querySelector('[data-instrument="1"] .instrument-name').dispatchEvent(new MouseEvent('click',{bubbles:true,ctrlKey:true}));`);
 assert.deepEqual(await evaluate(`[s.active,[...document.querySelectorAll('.instrument.selected')].map(e=>Number(e.dataset.instrument)),[...s.selection]]`),[1,[0,1],[1]]);
 await evaluate(`document.getElementById('canvas').dispatchEvent(new KeyboardEvent('keydown',{key:'a',ctrlKey:true,bubbles:true}));`);
 assert.equal(await evaluate('s.selection.size'),5);
 assert.deepEqual(await evaluate(`geometry.boxIds({tick:0,pitch:0},{tick:160,pitch:127}).sort()`),[1,2,3,4,5]);
 await evaluate(`clip.copyNotes();clip.pasteNotes();`);
 assert.deepEqual(await evaluate(`s.project.notes.slice(-5).map(n=>[n.instrument,n.start,n.volume])`),[[1,128,13],[1,128,5],[1,160,5],[1,160,3],[1,192,3]]);
 await evaluate(`historyApi.undo();s.selection=new Set([1,4]);commands.refresh();const field=document.getElementById('volume');field.value='7';field.dispatchEvent(new Event('change'));`);
 assert.deepEqual(await evaluate(`s.project.notes.filter(n=>s.selection.has(n.id)).map(n=>n.volume)`),[7,7]);
 await evaluate(`historyApi.undo();s.selection=new Set([1,4]);toolbar.setTool('select');commands.refresh();const note=s.project.notes[0],r=geometry.rect(note),canvas=document.getElementById('canvas'),b=canvas.getBoundingClientRect();window.beforeMove=s.project.notes.map(n=>({...n}));for(const [type,dx] of [['pointerdown',0],['pointermove',96],['pointerup',96]])canvas.dispatchEvent(new PointerEvent(type,{clientX:b.left+r.x+10+dx,clientY:b.top+r.y+r.h/2,button:0,pointerId:1,bubbles:true}));`);
 assert.deepEqual(await evaluate(`s.project.notes.filter(n=>[1,4].includes(n.id)).map(n=>[n.start,n.instrument])`),[[32,0],[64,1]]);
 await evaluate(`historyApi.undo();const gain=document.querySelector('[data-instrument="1"] .instrument-gain input');gain.value='0';gain.dispatchEvent(new Event('input'));gain.dispatchEvent(new Event('change'));`);
 assert.deepEqual(await evaluate(`[s.project.instruments[1].volume,stateApi.isMuted(1),!!geometry.hit((()=>{const r=geometry.rect(s.project.notes.find(n=>n.id===4));return {x:r.x+5,y:r.y+r.h/2}})()),serialization.parse(JSON.stringify(s.project)).instruments[1].volume]`),[0,false,true,0]);
 assert.equal(await evaluate(`(()=>{const row=document.querySelector('[data-instrument="1"]');return row.querySelector('.instrument-controls').getBoundingClientRect().bottom<=row.querySelector('.instrument-gain').getBoundingClientRect().top&&row.querySelector('.instrument-gain').getBoundingClientRect().bottom<=row.querySelector('.instrument-actions').getBoundingClientRect().top;})()`),true);
 await evaluate('historyApi.undo()');assert.equal(await evaluate('s.project.instruments[1].volume??100'),100);
 await evaluate(`document.querySelector('[data-instrument="0"] .instrument-name').click();`);assert.deepEqual(await evaluate(`[s.active,[...document.querySelectorAll('.instrument.selected')].map(e=>Number(e.dataset.instrument))]`),[0,[0]]);
 await evaluate(`{toolbar.setTool('draw');const canvas=document.getElementById('canvas'),b=canvas.getBoundingClientRect(),r=geometry.rect({instrument:0,start:256,length:32,pitch:76});for(const type of ['pointerdown','pointerup'])canvas.dispatchEvent(new PointerEvent(type,{clientX:b.left+r.x+5,clientY:b.top+r.y+r.h/2,button:0,pointerId:2,bubbles:true}));}`);
 assert.equal(await evaluate('s.project.notes.at(-1).instrument'),0);
 await evaluate(`import('./dist/playback/transport.js').then(async transport=>{await transport.play();if(!document.getElementById('play').classList.contains('is-playing'))throw Error('Native playback did not start');const gain=document.querySelector('[data-instrument="0"] .instrument-gain input');gain.value='0';gain.dispatchEvent(new Event('input'));gain.dispatchEvent(new Event('change'));gain.value='50';gain.dispatchEvent(new Event('input'));gain.dispatchEvent(new Event('change'));transport.seekToTick(32);transport.stopPlayback(false);});`);
 checks.push('Native live synth accepts gain changes and seeking; drawn notes target the main instrument');
 checks.push('Ctrl-click main destination, Select All, box selection, cross-instrument move/velocity/copy, flattened paste, single-click reset, zero gain remains editable, slider placement, Undo and version-2 roundtrip');
 await evaluate(`s.project.instruments.push({name:'Instructions',color:'#abcdef',isInstructions:true},{name:'Bass',color:'#abcdef'},{name:'Flute',color:'#abcdef'});stateApi.selectInstrument(0);commands.refresh();window.pick=(index,options={})=>document.querySelector('[data-instrument="'+index+'"] .instrument-name').dispatchEvent(new MouseEvent('click',{bubbles:true,...options}));window.stack=()=>[s.active,s.selectedInstruments.size?[...s.selectedInstruments]:[s.active]];void 0;`);
 await evaluate('pick(4,{shiftKey:true})');assert.deepEqual(await evaluate('stack()'),[4,[0,1,3,4]]);
 await evaluate('pick(4,{ctrlKey:true})');assert.deepEqual(await evaluate('stack()'),[3,[0,1,3]]);
 await evaluate('s.selection=new Set([1,4]);pick(1,{ctrlKey:true})');assert.deepEqual(await evaluate('[stack(),[...s.selection]]'),[[3,[0,3]],[1]]);
 await evaluate('pick(3,{ctrlKey:true});pick(0,{ctrlKey:true})');assert.deepEqual(await evaluate('stack()'),[0,[0]]);
 await evaluate('pick(4);pick(0,{shiftKey:true})');assert.deepEqual(await evaluate('stack()'),[0,[4,3,1,0]]);
 await evaluate('pick(0,{ctrlKey:true})');assert.deepEqual(await evaluate('stack()'),[1,[4,3,1]]);
 await evaluate('pick(4,{shiftKey:true})');assert.deepEqual(await evaluate('stack()'),[4,[1,3,4]]);
 await evaluate('pick(4,{ctrlKey:true});pick(4,{ctrlKey:true})');assert.deepEqual(await evaluate('stack()'),[4,[1,3,4]]);
 await evaluate('pick(1)');assert.deepEqual(await evaluate('stack()'),[1,[1]]);
 checks.push('Shift ranges in both directions skip Instructions and reorder existing members; Ctrl removes main/non-main, prunes note selection, restores stack main, re-adds at top and protects the last instrument');
 fs.writeFileSync('.validation/electron-volume.png',(await win.webContents.capturePage()).toPNG());finish();
 }catch(error){finish(error);}});});require('../main.cjs');
