const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {compareVersions,findWindowsAsset,digestValue,downloadAsset,portableScript,createPortableUpdater}=require('../updater.cjs');

test('version comparison accepts current tags and orders the next semantic release',()=>{assert.equal(compareVersions('0.3.4.1','0.3.4'),1);assert.equal(compareVersions('v0.3.5','0.3.4.1'),1);assert.equal(compareVersions('0.3.5','0.3.5'),0);assert.throws(()=>compareVersions('latest','0.3.5'));});
test('the public Windows asset requires a valid GitHub SHA-256 digest',()=>{const asset={name:'MML.Music.Studio-win32-x64.zip',browser_download_url:'https://example.test/app.zip',digest:'sha256:'+'a'.repeat(64)};assert.equal(findWindowsAsset({draft:false,prerelease:false,assets:[asset]}),asset);assert.equal(digestValue(asset.digest),'a'.repeat(64));assert.equal(findWindowsAsset({draft:true,assets:[asset]}),null);assert.throws(()=>digestValue(null));});
test('download streams to a verified complete archive and rejects changed bytes',async()=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'mml-update-')),data=Buffer.from('portable release bytes'),digest='sha256:'+crypto.createHash('sha256').update(data).digest('hex'),target=path.join(directory,'app.zip');try{const fetchImpl=async()=>new Response(data);await downloadAsset({fetchImpl,url:'https://example.test/app.zip',target,size:data.length,digest});assert.ok(fs.readFileSync(target).equals(data));await assert.rejects(downloadAsset({fetchImpl,url:'https://example.test/app.zip',target,size:data.length,digest:'sha256:'+'0'.repeat(64)}),/SHA-256/);}finally{fs.rmSync(directory,{recursive:true,force:true});}});
test('packaged updater checks, prompts, downloads and hands off only newer releases',async()=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'mml-update-flow-')),data=Buffer.from('release'),digest='sha256:'+crypto.createHash('sha256').update(data).digest('hex'),release={tag_name:'0.3.5',draft:false,prerelease:false,assets:[{name:'MML.Music.Studio-win32-x64.zip',browser_download_url:'https://example.test/app.zip',size:data.length,digest}]};let ready,progress=[];const fetchImpl=async url=>url.includes('/releases/latest')?{ok:true,json:async()=>release}:new Response(data);const app={isPackaged:true,getVersion:()=> '0.3.4.1',getPath:()=>directory},win={isDestroyed:()=>false,setProgressBar:value=>progress.push(value)},dialog={showMessageBox:async()=>({response:0})};try{const updater=createPortableUpdater({app,dialog,getWindow:()=>win,onReady:value=>{ready=value;},fetchImpl,platform:'win32'});assert.equal((await updater.check()).status,'ready');assert.equal(ready.version,'0.3.5');assert.ok(fs.existsSync(ready.archive));assert.equal(progress.at(-1),-1);}finally{fs.rmSync(directory,{recursive:true,force:true});}});
test('development checkouts never schedule or fetch updates',async()=>{let fetched=false,scheduled=false;const updater=createPortableUpdater({app:{isPackaged:false},dialog:{},getWindow:()=>null,onReady:()=>{},fetchImpl:async()=>{fetched=true;},platform:'win32',schedule:()=>{scheduled=true;}});updater.start();assert.equal((await updater.check()).status,'skipped');assert.equal(fetched,false);assert.equal(scheduled,false);});
test('PowerShell handoff waits, validates the extracted app and restarts it',()=>{const script=portableScript({archive:"C:\\Update's\\app.zip",installDirectory:'C:\\MML Studio',executable:'C:\\MML Studio\\MML Music Studio.exe',pid:42,version:'0.3.5'});assert.match(script,/Get-Process -Id 42/);assert.match(script,/exactly one MML Music Studio\.exe/);assert.match(script,/resources\\app\\package\.json/);assert.match(script,/Start-Process -FilePath \$targetExe/);assert.match(script,/Update''s/);});
