import {installPlayback} from './playback/transport.ts';
import {installSegmentView} from './segment-view.ts';
import {installChrome} from './chrome.ts';
import {installTools} from './tools.ts';
import {installAppearance} from './appearance.ts';
import {view} from './dom.ts';
import {state} from './state.ts';
import {pitchTop} from './pitch-viewport.ts';
import {draw} from './painting.ts';
import {layout} from './viewport.ts';
import {refresh} from './commands.ts';
import {setTool} from './toolbar.ts';
import {installPointer} from './pointer.ts';
import {installToolbar} from './toolbar.ts';
import {installInspector} from './inspector.ts';
import {installInstruments} from './instruments.ts';
import {installAdvancedInstructions} from './advanced-instructions.ts';
import {installHistory} from './history.ts';
import {installKeyboard} from './keyboard.ts';
import {installFiles} from './files.ts';
import {installFileDrop} from './drop-files.ts';
import {installExport} from './export.ts';
// Composition root: wire modules once, then initialize the editor.

installPointer();
installChrome();
installTools();
installToolbar();
installSegmentView();
installInspector();
installInstruments();
installAdvancedInstructions();
installHistory();
installKeyboard();
installFiles();
installFileDrop();
installExport();
view.onscroll=draw;
new ResizeObserver(layout).observe(view);
setTool('draw');
refresh();
installAppearance();
view.scrollTop=pitchTop(state.topPitch,78);
draw();

installPlayback();
